### ISSUE TITLE
TC71B7~1_main.exe

### ISSUE THREAD

**Issue by RedspaceNull** [TCNOco/TcNo-Acc-Switcher#264]
**Happens when i run it**

**To Reproduce**
1. Go to Run Tcno Account Switcher

**Expected behavior**
A clear and concise description of what you expected to happen, if not already obvious.

![image](https://user-images.githubusercontent.com/100664407/198813801-bf95375e-eab8-45c2-bdca-bc30e7d95ff7.png)

**Desktop (please complete the following information):**
 - OS: [. Win 10 21H1]

even if i run the main exe its a blue screen thats it

**Comment by TCNOco** [comment]
I'm closing this much older issue as likely resolved since it's creation.

Please download the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest).
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
