### ISSUE TITLE
مشكلتي هذي

### ISSUE THREAD

**Issue by asgggwef** [TCNOco/TcNo-Acc-Switcher#268]
Error.
An error occurred while processing your request.
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.
![لقطة الشاشة 2022-11-09 133049](https://user-images.githubusercontent.com/117820686/200807101-b6da2ded-c310-47c6-9147-6de5e6942536.png)

**Comment by TCNOco** [comment]
Hi. A lot of development has happened with the Server back-end and the Client front-end since this issue's creation. Please try the latest release should you still be interested and let me know if it's improved, or still happening.

[Latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
