### ISSUE TITLE
Battlenet App Breaks every time I open it now

### ISSUE THREAD

**Issue by jsim0210** [TCNOco/TcNo-Acc-Switcher#291]
I added a Battletag for one of my accounts and now the entire battlenet app in Acc Switcher doesn't work. 
![Web capture_28-1-2023_161715_localhost](https://user-images.githubusercontent.com/75036727/215291482-10322357-21bd-4d94-ab1f-b77584ddef3e.jpeg)

**Comment by TCNOco** [comment]
I'm closing this much older issue as likely resolved since it's creation.

Please download the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest).
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
