### ISSUE TITLE
Forget user..deleted everything.

### ISSUE THREAD

**Issue by MrRawrrino89** [TCNOco/TcNo-Acc-Switcher#322]
It was fine until i just did the update about 20 seconds ago, and now when i hit or right clicked on one of my accounts as i don't use it anymore to hit forget it deleted the rest of my steam accounts i had on it?..now everytime i load up TcNo i get this error.

![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/86880907/e3cc1744-ae4f-4db4-ab67-81a599668ceb)

im in the folder with the config file thats opened and has all my  steam accounts there but its not reading it onto the program anymore?

**Comment by T4lk** [comment]
same happens to me

**Comment by RegLoiD** [comment]
Same. FFS I knew I shouldn't update shit that worked perfectly fine up untill now...

**Comment by RegLoiD** [comment]
> So, I've looked into this, as a few users are complaining about it... But for some reason, I can't recreate this on my system.
> 
> The fix: Restore the backup `loginusers.vdf` file called `loginusers.vdf_last`. You can find this in `C:\Program Files (x86)\Steam\config\loginusers.vdf_last`. Copy and rename this to just `loginusers.vdf`.
> 
> This should restore all your accounts.
> 
> Please would you send me your `loginusers.vdf` and `...vdf_last` files through Discord should you be able to recreate this issue.
> 
> Discord: https://discord.gg/MQS4SJpwPt I am `@troublechute`, just called `TroubleChute`

I've just sent you a message on Discord.

**Comment by TCNOco** [comment]
Alright, this should be fixed. The account switcher previously replaced `""` with `"`, as something somewhere caused an extra quote to appear, breaking the file... Now that issue is gone, and there may be other `""`'s appearing as they should, but being replaced by just one `"`, it breaks the file > clearing it.

The latest update has been released and fixes this issue. https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-07-05_00

Unfortunately, if using the `Forget` feature 'lost' your accounts, they are gone from the `loginusers.vdf` file in Steam's config folder.

There are backups as `loginusers.vdf_last`, which you can copy and rename, assuming the accounts are still in this file. You can find them in `C:\Program Files (x86)\Steam\config`.

You can also edit the `loginusers.vdf` file with a text editor and you may see a line that looks like this:

`"SkipOfflineModeWarning" "`

edit this line to be

`"SkipOfflineModeWarning" "0"`
