### ISSUE TITLE
failed to load steam/config/loginusers.vdf | 

### ISSUE THREAD

**Issue by BopDB** [TCNOco/TcNo-Acc-Switcher#327]
One day I opened tcno and every single one of my accounts was missing. I check my loginusers.vdf_last and loginusers.vdf_error and all of my accounts just seemingly disappeared into thin air and I have no idea how I am going to be able to recover all those accounts.

![image (18)](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/105138204/38ac3735-6720-4671-bbd9-6d8c120a83d2)

**Expected behavior**
When I open tcno, it should display about 15 accounts here

Win 10 22H2

**Comment by TCNOco** [comment]
I'm afraid that with the previous version before that latest update a `"` was removed, corrupting the file and clearing it... There isn't a way to get the accounts back other than using the `vdf_last` backup file or by copy/pasting an account block and just replacing the username -- This is probably the quickest way to get back up and running as accounts aren't actually 'forgotten' by steam and can still be swapped to.

This issue is fixed on the latest version.

I also plan on improving backups for accounts so this shouldn't happen again :)
