### ISSUE TITLE
new update available

### ISSUE THREAD

**Issue by FirstNitrogen** [TCNOco/TcNo-Acc-Switcher#367]
it always tells me that there is a new update is available and when im done with it its just the same a new update available when i start steam and click on my account it sends me to the change account menu on steam

**Comment by TCNOco** [comment]
Should be fixed :)

**Comment by recur74** [comment]
I have the same issue:
`Update found: 2023-07-05_00 [131,63 KB]
- Multiple fixes for Steam platform (clearing on forget account) and BattleNet closing games on switch

-------------------------------------------
Total updates found: 1
Total size: 131,63 KB
-------------------------------------------
Click the button below to start the update.

Closing TcNo Account Switcher instances (if any).
Downloading update: 2023-07-05_00
Download complete.
Extracting patch files
Applying patch...
Moving files...
Patch applied.

Verifying...Downloading latest hash list... 
File: hashes.json has MD5: 9008d7478121e1608cab927de3413d64 EXPECTED: db0cdd10c75f8649abff268ecc684879
Deleting: hashes.json
Downloading file from website...
File: Platforms.json has MD5: fa23839823f50d847722fdefe5683277 EXPECTED: 3feb3503f8b39cc5afc4ace5a517336c
Deleting: Platforms.json
Downloading file from website...
File: runas.dll has MD5: b220b43df7c367da1b1b5161be3fb127 EXPECTED: 232736e4ecf30a6f744ce939b2b581fd
Deleting: runas.dll
Downloading file from website...
File: runas.exe has MD5: 0 EXPECTED: 2c903fcd14a3fcf843f3e84e4fdd34ec
Deleting: runas.exe
Downloading file from website...
File: TcNo-Acc-Switcher-Globals.dll has MD5: a630997f1e4bd46c9d489b7909b5f884 EXPECTED: 9a74d3efa2d1ba5914dd429345dcdcdd
Deleting: TcNo-Acc-Switcher-Globals.dll
Downloading file from website...
File: TcNo-Acc-Switcher-Globals.pdb has MD5: 5b733776143e689bad57c618b51ee5b0 EXPECTED: 84a68a0ca6b5dc97aa7cf52a0399d805
Deleting: TcNo-Acc-Switcher-Globals.pdb
Downloading file from website...
File: TcNo-Acc-Switcher-Server.dll has MD5: a0be097fdb87cc4a993d00206cd72c62 EXPECTED: 4c4e86f43fbd8bec2a661f296fd2eaca
Deleting: TcNo-Acc-Switcher-Server.dll
Downloading file from website...
File: TcNo-Acc-Switcher-Server.exe has MD5: 0 EXPECTED: dcc883f6a5f04849a17c05a967e490de
Deleting: TcNo-Acc-Switcher-Server.exe
Downloading file from website...
File: TcNo-Acc-Switcher-Server.pdb has MD5: 237b78859ab2d5b68d8df81bea48b69a EXPECTED: 1a411c0e57f57fb10be012e603ad7b07
Deleting: TcNo-Acc-Switcher-Server.pdb
Downloading file from website...
File: TcNo-Acc-Switcher-Server_main.exe has MD5: 0 EXPECTED: 8ec81fca8aa35cc50fbb0506ffc65d7c
Deleting: TcNo-Acc-Switcher-Server_main.exe
Downloading file from website...
File: TcNo-Acc-Switcher-Tray.dll has MD5: 95b17f5a7fb689a449892392c152e5ea EXPECTED: 7998ade95bc761bf660accb5278e0441
Deleting: TcNo-Acc-Switcher-Tray.dll
Downloading file from website...
File: TcNo-Acc-Switcher-Tray.exe has MD5: 7cd87d0809deacb86d8757fd5e90f91b EXPECTED: dcc883f6a5f04849a17c05a967e490de
Deleting: TcNo-Acc-Switcher-Tray.exe
Downloading file from website...
File: TcNo-Acc-Switcher-Tray_main.exe has MD5: fd39a7e3f450b9762abbfb0c1a5eccdb EXPECTED: 9161df386fe37ac98d0738f5df6e984e
Deleting: TcNo-Acc-Switcher-Tray_main.exe
Downloading file from website...
File: TcNo-Acc-Switcher-Updater.dll has MD5: fb94fa4c19451efbaa91fe9e266f0b76 EXPECTED: 1e4230154d9e73bd436d3992c0e4d08e
Deleting: TcNo-Acc-Switcher-Updater.dll
Downloading file from website...
File: TcNo-Acc-Switcher.dll has MD5: 433f7ef19ea8c30910adfcd743bccec1 EXPECTED: b1c55d8fd3031f52fccb4bb968abdf90
Deleting: TcNo-Acc-Switcher.dll
Downloading file from website...
File: TcNo-Acc-Switcher.exe has MD5: 0 EXPECTED: dcc883f6a5f04849a17c05a967e490de
Deleting: TcNo-Acc-Switcher.exe
Downloading file from website...
File: TcNo-Acc-Switcher.pdb has MD5: 0feb0cf9b0f02fa5cfefa7c3a6926bca EXPECTED: c3c47352482583f4e68c24e5d89181e7
Deleting: TcNo-Acc-Switcher.pdb
Downloading file from website...
File: TcNo-Acc-Switcher_main.exe has MD5: 855dde2134eaf52889abd431feb0d6de EXPECTED: 96ea5355855b071b32b54fb70af97392
Deleting: TcNo-Acc-Switcher_main.exe
Downloading file from website...
File: _First_Run_Installer.exe has MD5: 551dbc5c5fc818debbbf7fd2b8f3e226 EXPECTED: 3271896001dd733f9400773d64957f1d
Deleting: _First_Run_Installer.exe
Downloading file from website...
File: Resources\en-US.yml has MD5: c2cea01dc8d08cb5600d3bb28fa9690d EXPECTED: 5bd48b99f942f7cebcb42e06ef1763b9
Deleting: Resources\en-US.yml
Downloading file from website...

Copying files to %AppData%/TcNo Account Switcher... (unless set otherwise)
Done.
Files verified!

Updating files in AppData!

All updates complete!`

After clicking "Start Acc Swither" in the "TcNo Account Switcher Updater" dialog. The update banner appears in the main window again. If you click it, the update starts again.

**Comment by beljim** [comment]
Same, I'm using the Portable version.

**Comment by TCNOco** [comment]
OK so:
- A few old versions have broken updater systems. They can't be saved automatically, and need to be manually updated. Get the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest).
- When I push updates, I also need to remember to clear Cloudflare's cache. The hashes file is sometimes older, requiring files that don't exist, or otherwise getting it stuck in an update loop. I'll need to remember this but do forget sometimes...

The latest update should have improvements.
Are you still experiencing this issue now?

**Comment by TCNOco** [comment]
Closing this for now. The updates system was overhauled and should no longer be an issue :)
Thanks for your input.
