### ISSUE TITLE
all steam accoutns gone

### ISSUE THREAD

**Issue by Gaming-Gnome** [TCNOco/TcNo-Acc-Switcher#383]
i added a new steam account and now all my accounts dissapeared they are gone, i even lost access to some because i don't know the account name nor password.

**Comment by TCNOco** [comment]
The TcNo Account Switcher only works by reading and modifying Steam's `loginusers.vdf` file, that's managed by Steam.
You may be able to find and restore a previous version by checking: `C:\Program Files (x86)\Steam\config` for `loginusers.vdf_last`, `loginusers.vdf_temp`, or other copies.

**Comment by aaa-1427** [comment]
same problem
it's happened for 5 times

**Comment by klNuno** [comment]
same issue, sometimes just half the accounts diseappear
also after clicking on "Add a new account" and refreshing the app it breaks

**Comment by Akentrus** [comment]
I can confirm aswell it happens when modyfing anything meaning adding or removing accounts using the tool. Adding accounts by simply login into steam and check "remember me" works still and switching does too but as soon as you use the tool itself to modify anything it cannot read the file anymore and breaks.

**Comment by fontrendererobj** [comment]
same issue

**Comment by TCNOco** [comment]
Setup:
- Fresh install of both Steam, TcNo Account Switcher and Windows 11.
- Steam sign in: Username, Password, Remember Me checked.
- Account shows in TcNo Account Switcher

Steps I tried:
- Click `Add New` with Steam open.
- Sign in with second account details
- Click `Back` and `Steam` in account switcher. Both accounts now show.
- Double-click first account. Steam restarts and is using the first account.

Closing and restarting the TcNo Account Switcher still shows all accounts.
---
Clicking `Add New` in the account switcher, followed by refreshing still keeps things as is.
---
How is the Steam switching broken? What step am I missing to recreate this issue?

**Comment by klNuno** [comment]
hey @TCNOco

I'm currently using windows 10 if it matters, whenever I press add new account then right click -> refresh or if I do forget an account the app breaks.

Lmk I can still reproduce the issue right now

**Comment by TCNOco** [comment]
This should be fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
I assume most has to do with Steam's built-in account switcher. This is now being disabled by the TcNo Account Switcher when switching accounts. Using Steam's built-in account switcher may break functionality of this program.

You can re-enable in Steam (Steam > Settings > Interface > Ask which account to use each time Steam starts), or tick a box in TcNo Account Switcher > Steam > Settings.

**Comment by klNuno** [comment]
@TCNOco It works thank you so much ! <333

Is it possible that you can check this again ? idk if it's complicated to do but that would be really helpful as well #230

**Comment by TCNOco** [comment]
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.

**Comment by runfio** [comment]
is there any "undo" system or anything of the sort? had the same thing happen to me except i meant to press note and i pressed forget on accident. wasnt in the config file unfortunately. if anyone could help at all it would be GREATLY appreciated.
*edit im reading the github and it says if you removed an account that you didnt mean to that i could restore it in the settings on the app but i cannot find it.
